<?php

namespace App\Services\Employee;

use App\Models\Employee;
use App\Services\BaseService;

class EmployeeService extends BaseService
{

    public function __construct(Employee $model)
    {
        $this->model = $model;
    }

    public function getAllPagination($where = [])
    {
        if (!empty(\request()->name)) {
            $where[] = ['name', 'like', '%' . \request()->name . '%'];
        }

        if (!empty(\request()->branchId)) {
            $where[] = ['branch_id', \request()->branchId];
        }

        if (!empty(\request()->type)) {
            $where[] = ['type', \request()->type];
        }
        return parent::getAllPagination($where); // TODO: Change the autogenerated stub
    }

    public function update($id, $data)
    {
        if(empty($data['password'])){
            unset($data['password']);
        }
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }
}
