<?php

namespace App\Services\Branch;


use App\Models\Branch;
use App\Models\Warehouse;
use App\Services\BaseService;
use Illuminate\Validation\ValidationException;

class BranchService extends BaseService
{

    public function __construct(Branch $model)
    {
       $this->model = $model;

    }


    public function delete($id)
    {
        $warehouse = Warehouse::where('branch_id', $id)->first();

        if ($warehouse) {
            $hasStock = $warehouse->warehouseMaterials()
                ->where('quantity', '>', 1)
                ->exists();

            if ($hasStock) {
                throw ValidationException::withMessages(['Cannot delete branch: warehouse contains items with quantity > 1.']);
            }
        }

        return parent::delete($id); // TODO: Change the autogenerated stub
    }

}
