<?php

namespace App\Http\Requests\Employee;

use App\Enum\EmployeeTypeEnum;
use App\Http\Requests\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CreateEmployeeRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'branch_id' => [Rule::exists('branches', 'id')->whereNull('deleted_at'), 'required'],
            'name' => 'required',
            'user_name' => [Rule::unique('employees')->whereNull('deleted_at'),'required'],
            'password' => 'string|min:8|required',
            'type' => [Rule::in(EmployeeTypeEnum::toArray()), 'required'],
            'phone' => [Rule::unique('employees')->whereNull('deleted_at'),'required','phone:sy'],
            'address' => 'required',
            'age' => 'required|integer|between:15,60',
            'skill' => 'required',
            'last_job' => 'required',
        ];
    }


    public function messages()
    {
        return [
            'phone.phone' => 'the number must be 09********',
        ]; // TODO: Change the autogenerated stub
    }
}
