<?php

namespace App\Services\Item;

use App\Exceptions\ValidationException;
use App\Http\Requests\Category\CategoryIdRequest;
use App\Http\Requests\Item\ShowItemsRequest;
use App\Models\Item;
use App\Models\ItemImage;
use App\Services\BaseService;
use App\Traits\FileTrait;

class ItemService extends BaseService
{
    use FileTrait;

    public function __construct(Item $model)
    {
        $this->model = $model;
    }

    public function getAll($where = [])
    {
        if (!empty(\request()->categoryId)){
            $data = app(ShowItemsRequest::class)->validated();
            $where = [
                'category_id' => $data['categoryId'],
            ];
        }
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }

    public function AddItemImages($id,$images){
        foreach ($images as $image){
        $image = $this->uploadFile($image,'Items/');
        ItemImage::create([
            'item_id' => $id,
            'image' => $image
        ]);
        }
    }

    public function DeleteItemImages($images){
        $imageIds = $images;
        $images = ItemImage::whereIn('id',$imageIds)->get();
        $count = ItemImage::whereNotIn('id', $imageIds)->count();
        if ($count < 1){
            throw new ValidationException('The item should be have 1 image at least');
        }
        foreach ($images as $image){
            $this->deleteFile($image->image);
        }
        $images->each->delete();
    }

}
