<?php

namespace App\Http\Requests\TableReservation;

use App\Http\Requests\BaseRequest;
use App\Rules\ReservationAvailable;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class CreateTableReservationRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'branch_id' => [Rule::exists('branches','id')->whereNull('deleted_at'),'required'],
            'date' => [
                'required',
                'date',
                'after:today',
            ],
            'from_time' => [
                'required',
                'date_format:H:i',
            ],
            'to_time' => [
                'required',
                'date_format:H:i',
                'after:from_time',
                function ($attribute, $value, $fail) {
                    if ($this->branch_id && $this->date && $this->from_time && $this->chairs) {
                        (new ReservationAvailable(
                            $this->branch_id,
                            $this->date,
                            $this->from_time,
                            $value,
                            $this->chairs
                        ))->validate($attribute, $value, $fail);
                    }
                },
            ],
            'chairs' => 'required|integer|min:2',
        ];
    }

public function messages()
{
    return [
        'chairs.min' => 'the minimum chairs is 2',
    ]; // TODO: Change the autogenerated stub
}
}
