<?php

namespace App\Services\Discount;

use App\Models\Discount;
use App\Services\BaseService;

class DiscountService extends BaseService
{

    public function __construct(Discount $model)
    {
        $this->model = $model;
    }

    public function getAll($where = [])
    {
        Discount::where('to_date','<',\now())->delete();
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }
}
