<?php

namespace App\Services\Discount;

use App\Http\Requests\Discount\ShowDiscountsRequest;
use App\Models\Discount;
use App\Services\BaseService;
use App\Services\Notification\NotificationService;

class DiscountService extends BaseService
{

    public function __construct(Discount $model,public NotificationService $service)
    {
        $this->model = $model;
    }

    public function getAll($where = [])
    {
        $data = app(ShowDiscountsRequest::class);
        $this->service->sendNotification("caNkqFelTtu5aU3f8WMF-N:APA91bHabmr5PJ3XACxe9fNbNEI0ke8irle60vZKLemiKzB5Gv8n0dNoIXRug0ahdSvXtNQ8OQ1E0QJi4QmwEGFmJIKwMHENe890MT33twGvViTSJ1ikjp8","zaina","test");
        Discount::where('to_date','<',\now())->delete();
        if (!empty($data['search'])){
         $where[] = ['code','=',$data['search']];
        }
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }
}
