<?php

namespace App\Services\InternalOrder;

use App\Enum\OrderStatusEnum;
use App\Enum\OrderTypeEnum;
use App\Exceptions\ValidationException;
use App\Http\Requests\InternalOrder\GetInternalOrdersRequest;
use App\Models\InternalOrder;
use App\Models\InternalOrderItem;
use App\Models\InternalOrderOffer;
use App\Models\Invoice;
use App\Models\Item;
use App\Models\Offer;
use App\Services\BaseService;

class InternalOrderService extends BaseService
{
    public function __construct(InternalOrder $model)
    {
        $this->model = $model;
    }

    public function create($data)
    {
        $waiter = \auth('Employee')->user();
        $branch_id = $waiter->branch_id;
        $data['waiter_id'] = $waiter->id;
        $data['branch_id'] = $branch_id;
        $invoice = Invoice::firstOrCreate(
            [
                'table_id' => $data['table_id'],
                'branch_id' => $data['branch_id'],
                'status' => OrderStatusEnum::PENDING,
            ],
            [
                'table_id' => $data['table_id'],
                'branch_id' => $data['branch_id'],
            ]
        );
        $data['invoice_id'] = $invoice->id;
        $data['type'] = OrderTypeEnum::INT;
        return parent::create($data); // TODO: Change the autogenerated stub
    }


    public function ChangeInternalOrderStatus($id, $data)
    {
        $internalOrder = $this->getOne($id);
        $internalOrder->update(['status' => $data['status']]);
    }

    public function GetInternalOrderItems($id)
    {
        $internalOrder = $this->getOne($id);
        $items = $internalOrder->InternalOrderLines;
        $offerItems = $internalOrder->internalOrderOffers;
        $res['items'] = $items;
        $res['offers'] = $offerItems;
        return $res;
    }


    public function getAllPagination($where = [])
    {
        $data = \app(GetInternalOrdersRequest::class);
        if (!empty($data['status'])) {
            $where[] = ['status' , $data['status']];
        }
        return parent::getAllPagination($where); // TODO: Change the autogenerated stub
    }

    public function update($id, $data)
    {
        $internalOrder = $this->getOne($id);
        $invoice = $internalOrder->Invoice;
        $waiter = \auth('Employee')->user();
        $branch_id = $waiter->branch_id;
        $data['branch_id'] = $branch_id;
        if ($invoice->branch_id != $data['branch_id']){
            throw new ValidationException('The internal Order not in this branch');
        }

        $invoice->decrement('full_price',$internalOrder->full_price);

        $internalOrder->InternalOrderLines()->delete();
        $internalOrder->InternalOrderOffers()->delete();

        $full_price = 0.00;
        $items = $data['items'];
        $offers = $data['offers'];
        if (!empty($items)) {
            $full_price += $this->AddInternalOrderItems($internalOrder->id, $items);
        }

        if (!empty($offers)) {
            $full_price += $this->AddInternalOrderoffers($internalOrder->id, $offers);
        }
        $internalOrder->update(['full_price' => $full_price,'status' => OrderStatusEnum::WAITING]);
        $invoice->increment('full_price', $full_price);

    }


    private function AddInternalOrderItems($id, $items)
    {
        $price = 0.00;
        foreach ($items as $item) {
            $neededItem = Item::find($item['item_id']);
            $internalOrderItem = InternalOrderItem::create([
                'internal_order_id' => $id,
                'item_id' => $item['item_id'],
                'quantity' => $item['quantity'],
                'price' => $item['quantity'] * $neededItem->price
            ]);
            $price += $internalOrderItem->price;
        }
        return $price;
    }

    private function AddInternalOrderoffers($id, $offers)
    {
        $price = 0.00;
        foreach ($offers as $offer) {
            $neededOffer = Offer::find($offer['offer_id']);
            $internalOrderOffer = InternalOrderOffer::create([
                'internal_order_id' => $id,
                'offer_id' => $offer['offer_id'],
                'quantity' => $offer['quantity'],
                'price' => $offer['quantity'] * $neededOffer->price
            ]);
            $price += $internalOrderOffer->price;
        }
        return $price;
    }
}
