<?php

namespace App\Services\InternalOrder;

use App\Enum\OrderStatusEnum;
use App\Http\Requests\InternalOrder\GetInternalOrdersRequest;
use App\Models\InternalOrder;
use App\Models\Invoice;
use App\Services\BaseService;

class InternalOrderService extends BaseService
{
    public function __construct(InternalOrder $model)
    {
        $this->model = $model;
    }

    public function create($data)
    {
        $invoice = Invoice::firstOrCreate(
            [
                'table_id' => $data['table_id'],
                'branch_id' => $data['branch_id'],
            ],
            [
                'table_id' => $data['table_id'],
                'branch_id' => $data['branch_id'],
            ]
        );
        $data['invoice_id'] = $invoice->id;
        return parent::create($data); // TODO: Change the autogenerated stub
    }


    public function ChangeInternalOrderStatus($id, $data)
    {
        $internalOrder = $this->getOne($id);
        $internalOrder->update(['status' => $data['status']]);
    }

    public function GetInternalOrderItems($id)
    {
        $internalOrder = $this->getOne($id);
        $items = $internalOrder->InternalOrderLines;
        $offerItems = $internalOrder->internalOrderOffers;
        $res['items'] = $items;
        $res['offers'] = $offerItems;
        return $res;
    }


    public function getAllPagination($where = [])
    {
        $data = \app(GetInternalOrdersRequest::class);
        if (!empty($data['status'])) {
            $where[] = ['status' , $data['status']];
        }
        return parent::getAllPagination($where); // TODO: Change the autogenerated stub
    }
}
