<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\BaseCRUDController;
use App\Http\Controllers\Controller;
use App\Http\Requests\Employee\CreateEmployeeRequest;
use App\Http\Requests\Employee\EmployeeIdRequest;
use App\Http\Requests\Employee\ShowEmployeesRequest;
use App\Http\Requests\Employee\UpdateEmployeeRequest;
use App\Services\BaseService;
use App\Services\Employee\EmployeeService;
use Illuminate\Http\Request;

class EmployeeController extends BaseCRUDController
{
    public function __construct(EmployeeService $service)
    {
        $this->service = $service;
        $this->createRequest = CreateEmployeeRequest::class;
        $this->updateRequest = UpdateEmployeeRequest::class;
        $this->idRequest = EmployeeIdRequest::class;
    }


    protected function indexPagination()
    {
        \app(ShowEmployeesRequest::class);
        return parent::indexPagination(); // TODO: Change the autogenerated stub
    }
}
