<?php

namespace App\Http\Requests\Rate;

use App\Http\Requests\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CreateRateRequest extends BaseRequest
{


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'branch_id' => [Rule::exists('branches','id')->whereNull('deleted_at'),'required'],
            'rate' => 'required|integer|min:1|max:5',
            'description' => 'nullable',
        ];
    }

    public function messages()
    {
        return [
            'rate.min' => 'the rate between 1 and 5',
        ] ;// TODO: Change the autogenerated stub
    }
}
