<?php

namespace App\Services\PurchaseInvoice;

use App\Http\Requests\PurchaseInvoice\GetPaginationPurchaseInvoiceRequest;
use App\Models\PurchaseInvoice;
use App\Services\BaseService;
use http\Encoding\Stream\Debrotli;

class PurchaseInvoiceService extends BaseService
{

    public function __construct(PurchaseInvoice $model)
    {
        $this->model = $model;
    }

    public function GetPurchaseInvoiceLines($id,$data){
        $purchaseInvoice = PurchaseInvoice::find($id);
        $purchaseInvoiceLines = $purchaseInvoice->PurchaseInvoiceLines;
        return $purchaseInvoiceLines;
    }

    public function getAllPagination($where = [])
    {
        $data = \app(GetPaginationPurchaseInvoiceRequest::class);
        if (!empty($data['branchId'])){
            $where[] = ['branch_id' , $data['branchId']];
        }
        return parent::getAllPagination($where); // TODO: Change the autogenerated stub
    }
}
