<?php

namespace App\Services\Offer;

use App\Http\Requests\Offer\GetAllOffersRequest;
use App\Models\Offer;
use App\Services\BaseService;
use Illuminate\Support\Carbon;

class OfferService extends BaseService
{

    public function __construct(Offer $model)
    {
        $this->model = $model;
    }

    public function getAllPagination($where = [])
    {
        $data = \app(GetAllOffersRequest::class);

        if (!empty($data['search'])) {
            $where[] = ['name', 'like', '%' . $data['search'] . '%'];
        }

        $offers = Offer::where($where);

        if (!empty($data['branchId'])) {

            $offers->whereHas('OfferBranches', function ($query) use ($data) {
                $query->where('branch_id', $data['branchId']);
            });

        }

        if (isset($data['active'])) {
            if ($data['active'] == 1) {
                $offers->whereDate('from_date', '<=', Carbon::today())
                    ->whereDate('to_date', '>=', Carbon::today());
            } else {
                $offers->where(function ($query) {
                    $query->whereDate('to_date', '<', Carbon::today())
                        ->orWhereDate('from_date', '>', Carbon::today());
                });
            }
        }
        $perPage = \request()->header('perPage',10);
        return $offers->paginate($perPage)->toArray();
       //return parent::getAllPagination($where); // TODO: Change the autogenerated stub
    }

}
