<?php

namespace App\Services\Category;

use App\Models\Category;
use App\Services\BaseService;
use App\Traits\FileTrait;

class CategoryService extends BaseService
{
    use FileTrait;

    public function __construct(Category $model)
    {
        $this->model = $model;
    }


    public function create($data)
    {
        $data['image'] = $this->uploadFile($data['image'], 'Categories/');
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($id, $data)
    {
        $category = Category::find($id);
        if (empty($data['image'])) {
            unset($data['image']);
        } else {
            $data['image'] = $this->uploadFile($data['image'], 'Categories/');
            $this->deleteFile($category->image);
        }
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

}
