<?php

namespace App\Services\WarehouseMaterial;

use App\Http\Requests\WarehouseMaterial\GetWarehouseMaterialRequest;
use App\Http\Requests\WarehouseMaterial\RemoveWarehouseMaterialsRequest;
use App\Models\Branch;
use App\Models\Warehouse;
use App\Models\WarehouseMaterial;
use App\Services\BaseService;

class WarehouseMaterialService extends BaseService
{

    public function __construct(WarehouseMaterial $model)
    {
        $this->model = $model;
    }

    public function getAll($where = [])
    {
        \app(GetWarehouseMaterialRequest::class);
        $warehouse = Warehouse::where('branch_id', \request()->branchId)->first();
        $where['warehouse_id'] = $warehouse?->id;
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }

    public function AddWarehouseMaterials($data)
    {
        $branch = Branch::find($data['branch_id']);
        $warehouse = $branch->Warehouse;
        foreach ($data['materials'] as $material) {
            WarehouseMaterial::where([
                'warehouse_id' => $warehouse->id,
                'material_id' => $material['material_id'],
            ])->first()->increment('quantity', $material['quantity']);
        }
    }

    public function RemoveWarehouseMaterials($data)
    {
        $branch = Branch::find($data['branch_id']);
        $warehouse = $branch->Warehouse;
        foreach ($data['materials'] as $material) {
            WarehouseMaterial::where([
                'warehouse_id' => $warehouse->id,
                'material_id' => $material['material_id'],
            ])->first()->decrement('quantity', $material['quantity']);
        }
    }
}
