<?php

namespace App\Services\WarehouseMaterial;

use App\Http\Requests\WarehouseMaterial\GetWarehouseMaterialRequest;
use App\Models\Warehouse;
use App\Models\WarehouseMaterial;
use App\Services\BaseService;

class WarehouseMaterialService extends BaseService
{

    public function __construct(WarehouseMaterial $model)
    {
        $this->model = $model;
    }

    public function getAll($where = [])
    {
        \app(GetWarehouseMaterialRequest::class);
        $warehouse = Warehouse::where('branch_id',\request()->branchId)->first();
        $where['warehouse_id'] = $warehouse?->id;
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }


}
