<?php

namespace App\Http\Controllers\Table;

use App\Http\Controllers\BaseCRUDController;
use App\Http\Controllers\Controller;
use App\Http\Requests\Table\CreateTableRequest;
use App\Http\Requests\Table\ShowTablesRequest;
use App\Http\Requests\Table\TableChangeStatusRequest;
use App\Http\Requests\Table\TableIdRequest;
use App\Http\Requests\Table\UpdateTableRequest;
use App\Services\Table\TableService;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class TableController extends BaseCRUDController
{
    public function __construct(TableService $service)
    {
        $this->service = $service;
        $this->createRequest = CreateTableRequest::class;
        $this->idRequest = TableIdRequest::class;
        $this->updateRequest = UpdateTableRequest::class;
    }

    protected function indexPagination()
    {
        \app(ShowTablesRequest::class);
        return parent::indexPagination(); // TODO: Change the autogenerated stub
    }

    public function TableChangeStatus($id,TableChangeStatusRequest $request)
    {
        $data = Arr::only($request->validated(), ['id']);
        $this->service->TableChangeStatus($id);
        return $this->sendResponse(__('custom.Success'));
    }
}
