<?php

namespace App\Http\Requests\Item;

use App\Http\Requests\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CreateItemRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'category_id' => [Rule::exists('categories','id')->whereNull('deleted_at'),'required'],
            'name' => [Rule::unique('items')->whereNull('deleted_at'),'required'],
            'price' => 'required|min:1000|numeric',
            'images' => 'required|array',
            'images.*' => 'required|image',
        ];
    }

    public function messages()
    {
        return [
            'price.min' => 'the minimum price is 1000',
        ]; // TODO: Change the autogenerated stub
    }
}
