<?php

namespace App\Services\Table;

use App\Models\Table;
use App\Services\BaseService;

class TableService extends BaseService
{
    public function __construct(Table $model)
    {
        $this->model = $model;
    }

    public function create($data)
    {
        $maxTableNumber = $this->model::where('branch_id',$data['branch_id'])->max('table_number') ;
        $data['table_number'] = ($maxTableNumber ?? 0) + 1;;
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function getAllPagination($where = [])
    {
        if (!empty(\request()->branchId)) {
            $where[] = ['branch_id', \request()->branchId];
        }

        if (isset(\request()->available)) {
            $where[] = ['available', \request()->available];
        }
        return parent::getAllPagination($where); // TODO: Change the autogenerated stub
    }
}
