<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Invoice extends Model
{
    use HasFactory;

    protected $primaryKey = 'id';

    protected $appends = ['branch_name'];

    protected $fillable = [
        'table_id',
        'branch_id',
        'full_price',
        'discount',
        'tax',
        'final_price',
        'status'
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    protected $casts = [
        'full_price' => 'integer',
        'discount' => 'integer',
        'tax' => 'integer',
        'final_price' => 'integer',
    ];

    /** @noinspection PhpUnused */
    public function getBranchNameAttribute()
    {
        $name = $this->Branch->name;
        unset($this->Branch);
        return $name;
    }


    public function toArray()
    {
        $this->load([
            'InternalOrders',
            'InternalOrders.InternalOrderLines',
            'InternalOrders.InternalOrderOffers',
            'InvoiceTaxes',
            'InvoiceDiscounts',
        ]);
        return parent::toArray(); // TODO: Change the autogenerated stub
    }


    public function Table(): BelongsTo
    {
        return $this->belongsTo(Table::class, 'table_id');
    }

    public function Branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class, 'branch_id');
    }

    public function InternalOrders(): HasMany
    {
        return $this->hasMany(InternalOrder::class, 'invoice_id');
    }

    public function InvoiceDiscounts(): HasMany
    {
        return $this->hasMany(InvoiceDiscount::class, 'invoice_id');
    }

    public function InvoiceTaxes(): HasMany
    {
        return $this->hasMany(InvoiceTax::class, 'invoice_id');
    }
}
