<?php

namespace App\Services\ExternalOrder;

use App\Models\Discount;
use App\Models\ExternalOrderInformation;
use App\Models\InternalOrder;
use App\Models\Invoice;
use App\Models\InvoiceDiscount;
use App\Models\InvoiceTax;
use App\Models\Tax;
use App\Services\BaseService;

class ExternalOrderService extends BaseService
{

    public function __construct(InternalOrder $model)
    {
        $this->model = $model;
    }

    public function create($data)
    {
        $invoice = Invoice::create([
            'branch_id' => $data['branch_id'],
        ]);
        $data['invoice_id'] = $invoice->id;
        $this->AddExternalOrderInformation($invoice->id,$data);
        $externalOrder =  parent::create($data); // TODO: Change the autogenerated stub
        $invoice = Invoice::find($invoice->id);
        if (!empty($data['discount_code'])){
            $this->AddInvoiceDiscount($invoice,$data['discount_code']);
        }

        $this->AddInvoiceTaxes($invoice);
        $final_price = $invoice->full_price + $invoice->tax - $invoice->discount;
        $invoice->update(['final_price' => $final_price]);
        return $externalOrder;
    }

    private function AddExternalOrderInformation($id, $data)
    {
        ExternalOrderInformation::create([
            'invoice_id' => $id,
            'user_id' => $data['user_id'],
            'location' => $data['location'],
            'phone' => $data['phone'],
        ]);
    }

    private function AddInvoiceDiscount($invoice, $discount_code)
    {
        $discount = Discount::where('code' , $discount_code)->first();
        $amount = ($discount->percent * $invoice->full_price) / 100 ;
        InvoiceDiscount::create([
            'invoice_id' => $invoice->id,
            'discount_id' => $discount->id,
            'percent' => $discount->percent,
            'amount' => $amount,
        ]);
        $invoice->update(['discount' => $amount]);
    }

    private function AddInvoiceTaxes($invoice)
    {

        $taxes = Tax::get();
        foreach ($taxes as $tax){
            $amount = ($tax->percent * $invoice->full_price) / 100 ;
            InvoiceTax::create([
                'invoice_id' => $invoice->id,
                'tax_id' => $tax->id,
                'percent' => $tax->percent,
                'amount' => $amount
            ]);
            $invoice->increment('tax',$amount);
        }
    }
}
