<?php

namespace App\Services\ExternalOrder;

use App\Enum\OrderStatusEnum;
use App\Enum\OrderTypeEnum;
use App\Exceptions\ValidationException;
use App\Models\Discount;
use App\Models\ExternalOrderInformation;
use App\Models\InternalOrder;
use App\Models\Invoice;
use App\Models\InvoiceDiscount;
use App\Models\InvoiceTax;
use App\Models\Tax;
use App\Services\BaseService;
use Illuminate\Support\Facades\Storage;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class ExternalOrderService extends BaseService
{

    public function __construct(InternalOrder $model)
    {
        $this->model = $model;
    }

    public function create($data)
    {
        $invoice = Invoice::create([
            'branch_id' => $data['branch_id'],
        ]);
        $data['invoice_id'] = $invoice->id;
        $data['type'] = OrderTypeEnum::EXT;
        $externalOrder = parent::create($data); // TODO: Change the autogenerated stub
        $this->AddExternalOrderInformation($invoice->id,$externalOrder->id, $data);
        $invoice = Invoice::find($invoice->id);
        if (!empty($data['discount_code'])) {
            $this->AddInvoiceDiscount($invoice, $data['discount_code']);
        }

        $this->AddInvoiceTaxes($invoice);
        $final_price = $invoice->full_price + $invoice->tax - $invoice->discount;
        $invoice->update(['final_price' => $final_price]);
        return $externalOrder;
    }

    private function AddExternalOrderInformation($invoice_id,$external_order_id, $data)
    {
        if (!file_exists(storage_path('invoices'))) {
            mkdir(storage_path('invoices'), 0755, true);
        }

        QrCode::format('svg')->generate($external_order_id, storage_path('invoices/invoice' . $external_order_id . '.svg'));

        ExternalOrderInformation::create([
            'invoice_id' => $invoice_id,
            'user_id' => $data['user_id'],
            'location' => $data['location'],
            'phone' => $data['phone'],
            'qr' => Storage::url('invoices/invoice' . $external_order_id . '.svg'),
        ]);
    }

    private function AddInvoiceDiscount($invoice, $discount_code)
    {
        $discount = Discount::where('code', $discount_code)->first();
        $amount = ($discount->percent * $invoice->full_price) / 100;
        InvoiceDiscount::create([
            'invoice_id' => $invoice->id,
            'discount_id' => $discount->id,
            'percent' => $discount->percent,
            'amount' => $amount,
        ]);
        $invoice->update(['discount' => $amount]);
    }

    private function AddInvoiceTaxes($invoice)
    {

        $taxes = Tax::get();
        foreach ($taxes as $tax) {
            $amount = ($tax->percent * $invoice->full_price) / 100;
            InvoiceTax::create([
                'invoice_id' => $invoice->id,
                'tax_id' => $tax->id,
                'percent' => $tax->percent,
                'amount' => $amount
            ]);
            $invoice->increment('tax', $amount);
        }
    }

    public function ChangeExternalOrderStatus($id, $data)
    {
        $externalOrder = $this->getOne($id);
        $externalOrder->update(['status' => $data['status']]);
    }


    public function AcceptExternalOrder($id, $data)
    {
        $externalOrder = $this->getOne($id);
        if ($externalOrder->Invoice->ExternalOrderInformation->user_id != $data['user_id']){
            throw new  ValidationException('this approve not to the same user');
        }
        $externalOrder->update(['status' => OrderStatusEnum::DONE]);
        $externalOrder->Invoice->update(['status' => OrderStatusEnum::DONE]);
    }
}
