<?php

namespace App\Services\Rate;

use App\Http\Requests\Rate\ShowRatesRequest;
use App\Models\Rate;
use App\Services\BaseService;

class RateService extends BaseService
{

    public function __construct(Rate $model)
    {
        $this->model = $model;
    }

    public function create($data)
    {
        $data['user_id'] = 1;
        return parent::create($data); // TODO: Change the autogenerated stub
    }


    public function getAll($where = [])
    {
        $data = \app(ShowRatesRequest::class)->validated();
        if (!empty($data['rate'])){
            $where['rate'] = $data['rate'];
        }
        if (!empty($data['userId'])){
            $where['user_id'] = $data['userId'];
        }
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }
}
